<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WechatRobot.Application\WechatRobot.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <PackageReference Include="PDFtoImage" />
    <PackageReference Include="UglyToad.PdfPig" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
