// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WechatRobot.Infrastructure.Persistence;

#nullable disable

namespace WechatRobot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WechatRobotDbContext))]
    partial class WechatRobotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("WorkToolDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime?>("WorkToolDisplayNameUpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("WorkToolDisplayName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.AdministrationAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SanitizedDetailJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("administration_audit", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConversationSessionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("inbound");

                    b.Property<string>("FallbackHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("FallbackWindowStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GroupRemark")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("InReplyToMessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("completed");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RobotConfigId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("user");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("SessionSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("StableSenderId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TerminalDecision")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TerminalEvidenceJson")
                        .HasColumnType("json");

                    b.Property<string>("TerminalReason")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkToolMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GroupProfileId");

                    b.HasIndex("InReplyToMessageId")
                        .IsUnique();

                    b.HasIndex("RobotConfigId");

                    b.HasIndex("WorkToolMessageId")
                        .IsUnique();

                    b.HasIndex("ConversationSessionId", "SessionSequence")
                        .IsUnique();

                    b.HasIndex("FallbackHash", "FallbackWindowStartUtc")
                        .IsUnique();

                    b.ToTable("conversation_message", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.ConversationSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ClearedThroughSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderScopeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupProfileId", "SenderScopeKey")
                        .IsUnique();

                    b.ToTable("conversation_session", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.DeadLetterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DurableJobId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid?>("SendCommandId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DurableJobId")
                        .IsUnique();

                    b.ToTable("dead_letter", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.DurableJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RelatedConversationMessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedConversationMessageId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("durable_job", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupHumanAgentEntity", b =>
                {
                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DefaultGroupProfileId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("char(36)")
                        .HasComputedColumnSql("CASE WHEN `IsDefault` = 1 AND `IsEnabled` = 1 THEN `GroupProfileId` ELSE NULL END", true);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("Stale");

                    b.Property<string>("WorkToolDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("GroupProfileId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DefaultGroupProfileId")
                        .IsUnique();

                    b.ToTable("group_human_agent", null, t =>
                        {
                            t.HasCheckConstraint("CK_group_human_agent_verification_status", "`VerificationStatus` IN ('Verified','Missing','Conflict','Stale')");
                        });
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ContextHistoryTurns")
                        .HasColumnType("int");

                    b.Property<int?>("ContextIdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("ContextIncludeBotHistory")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ContextSenderIsolated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ContextSummaryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ContextTokenCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalGroupId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("HandoffPausePolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("Group");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RegistrationSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Manual");

                    b.Property<Guid>("RobotConfigId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkToolGroupRemark")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("WorkToolImportedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("WorkToolLastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RobotConfigId", "Name", "WorkToolGroupRemark");

                    b.ToTable("group_profile", null, t =>
                        {
                            t.HasCheckConstraint("CK_group_profile_handoff_pause_policy", "`HandoffPausePolicy` IN ('Group','Sender')");

                            t.HasCheckConstraint("CK_group_profile_registration_source", "`RegistrationSource` IN ('Manual','WorkToolImport')");
                        });
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileTagEntity", b =>
                {
                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnowledgeTagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GroupProfileId", "KnowledgeTagId");

                    b.HasIndex("KnowledgeTagId");

                    b.ToTable("group_profile_tag", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExcludePattern")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("ExcludePatternKind")
                        .HasColumnType("int");

                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IgnoreCase")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IncludePattern")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("IncludePatternKind")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RuleKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupProfileId");

                    b.ToTable("group_rule", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("FinalAnswer")
                        .HasColumnType("longtext");

                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PauseScope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("QuestionMessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RobotConfigId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StableSenderId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("StartIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("QuestionMessageId")
                        .IsUnique();

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("RobotConfigId");

                    b.HasIndex("StartIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("GroupProfileId", "State");

                    b.ToTable("handoff_case", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AuthenticatedUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuthenticationKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("HandoffCaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthenticatedUserId");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique();

                    b.HasIndex("HandoffCaseId");

                    b.ToTable("handoff_message", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffTransitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("HandoffCaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("HandoffCaseId", "Sequence")
                        .IsUnique();

                    b.ToTable("handoff_transition", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeCandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid>("HandoffCaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("KnowledgeDocumentVersionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<Guid>("QuestionMessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandoffCaseId")
                        .IsUnique();

                    b.HasIndex("KnowledgeDocumentVersionId")
                        .IsUnique();

                    b.HasIndex("QuestionMessageId");

                    b.ToTable("knowledge_candidate", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeadingsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("IsTable")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KnowledgeDocumentVersionId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SynonymsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int?>("TableColumns")
                        .HasColumnType("int");

                    b.Property<int?>("TableRows")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentVersionId", "Sequence")
                        .IsUnique();

                    b.ToTable("knowledge_chunk", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkPreviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeadingsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("IsTable")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KnowledgeDocumentVersionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OverlapPrefixCharacters")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SynonymsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int?>("TableColumns")
                        .HasColumnType("int");

                    b.Property<int?>("TableRows")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentVersionId", "Sequence")
                        .IsUnique();

                    b.ToTable("knowledge_chunk_preview", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkTagEntity", b =>
                {
                    b.Property<Guid>("KnowledgeChunkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnowledgeTagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("KnowledgeChunkId", "KnowledgeTagId");

                    b.HasIndex("KnowledgeTagId");

                    b.ToTable("knowledge_chunk_tag", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("ActiveCollectionExclusive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ActiveCollectionName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ActiveDistance")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("ActiveEmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveIndexGeneration")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActiveVersionId")
                        .IsConcurrencyToken()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleteRequested")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("knowledge_document", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IndexCollectionExclusive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IndexCollectionName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("IndexGeneration")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PreviewRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("SafeFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("StagedContent")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VectorDistance")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("KnowledgeDocumentId", "Version")
                        .IsUnique();

                    b.ToTable("knowledge_document_version", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeIndexJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dimension")
                        .HasColumnType("int");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("DrainUntilUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<bool>("IsCollectionExclusive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnowledgeDocumentVersionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PendingTagIdsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("PreviousActiveCollectionExclusive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PreviousActiveCollectionName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PreviousActiveDistance")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("PreviousActiveEmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviousActiveVersionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceIndexJobId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.HasIndex("SourceIndexJobId");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("KnowledgeDocumentVersionId", "Operation", "Status");

                    b.ToTable("knowledge_index_job", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeOcrPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BlocksJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("KnowledgeDocumentVersionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .IsConcurrencyToken()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentVersionId", "PageNumber")
                        .IsUnique();

                    b.ToTable("knowledge_ocr_page", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("KnowledgeCandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RevisedAnswer")
                        .HasColumnType("longtext");

                    b.Property<string>("TagIdsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("KnowledgeCandidateId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("knowledge_review", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGlobalPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("knowledge_tag", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.ModelConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ApiKeyVersion")
                        .HasColumnType("int");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ConfigurationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultConfigurationType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CASE WHEN `IsDefault` = 1 THEN `ConfigurationType` ELSE NULL END", true);

                    b.Property<string>("EncryptedApiKey")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastTestFailureSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("LastTestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TestedConfigurationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultConfigurationType")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("model_config", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.RetrievalAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("ConfidenceThreshold")
                        .HasColumnType("double");

                    b.Property<double?>("ConfidenceValue")
                        .HasColumnType("double");

                    b.Property<string>("ContextPolicy")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("ConversationMessageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("InputSummaryJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid?>("ModelConfigurationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMessageId")
                        .IsUnique();

                    b.HasIndex("ModelConfigurationId");

                    b.HasIndex("GroupProfileId", "CreatedAtUtc");

                    b.ToTable("retrieval_audit", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CallbackRouteCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CallbackSecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EncryptedCallbackSecret")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("EncryptedWorkToolRobotId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("PreviousCallbackSecretExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreviousCallbackSecretHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SendCoordinationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime?>("SendLeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SendLeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SendRateLimitPerMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<decimal>("SendRateTokens")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(50m);

                    b.Property<DateTime>("SendRateUpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkToolRobotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CallbackRouteCode")
                        .IsUnique();

                    b.HasIndex("WorkToolRobotId")
                        .IsUnique();

                    b.ToTable("robot_config", null, t =>
                        {
                            t.HasCheckConstraint("CK_robot_config_send_rate_limit", "`SendRateLimitPerMinute` BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.SendCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExternalDispatchStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReconciliationReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("RobotConfigId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("WorkToolCommandMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("WorkToolFailListJson")
                        .HasColumnType("json");

                    b.Property<DateTime?>("WorkToolResultAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WorkToolResultCode")
                        .HasColumnType("int");

                    b.Property<string>("WorkToolSuccessListJson")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("GroupProfileId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RobotConfigId");

                    b.HasIndex("WorkToolCommandMessageId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("send_command", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.SystemSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("system_setting", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.WorkToolOperationAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EncryptedCommandJson")
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)");

                    b.Property<DateTime?>("ExternalDispatchStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("ReconciledGroupProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReconciliationAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReconciliationNextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReconciliationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Result")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid?>("RobotConfigId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SanitizedRequestJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("WorkToolCommandMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("WorkToolCommandNumber")
                        .HasColumnType("int");

                    b.Property<string>("WorkToolFailListJson")
                        .HasColumnType("json");

                    b.Property<DateTime?>("WorkToolResultAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WorkToolResultCode")
                        .HasColumnType("int");

                    b.Property<string>("WorkToolSuccessListJson")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ReconciledGroupProfileId");

                    b.HasIndex("RobotConfigId");

                    b.HasIndex("WorkToolCommandMessageId")
                        .IsUnique();

                    b.HasIndex("ReconciliationStatus", "ReconciliationNextAttemptAtUtc")
                        .HasDatabaseName("IX_worktool_operation_audit_reconciliation_due");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("worktool_operation_audit", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.WorkToolOperationConfirmationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("worktool_operation_confirmation", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.WorkToolRateLimitBucketEntity", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("NextPermitAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("ScopeKey");

                    b.ToTable("worktool_rate_limit_bucket", (string)null);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.WorkerHeartbeatEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Name");

                    b.ToTable("worker_heartbeat", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ConversationSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConversationSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("RobotConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.ConversationSessionEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.DeadLetterEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.DurableJobEntity", null)
                        .WithMany()
                        .HasForeignKey("DurableJobId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.DurableJobEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("RelatedConversationMessageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupHumanAgentEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("RobotConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileTagEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeTagEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.GroupRuleEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffCaseEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("RobotConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffMessageEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthenticatedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.HandoffCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("HandoffCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.HandoffTransitionEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.HandoffCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("HandoffCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeCandidateEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.HandoffCaseEntity", null)
                        .WithMany()
                        .HasForeignKey("HandoffCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkPreviewEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkTagEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeChunkEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeTagEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeIndexJobEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeOcrPageEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeDocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeReviewEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.KnowledgeCandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.RetrievalAuditEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ConversationMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("ConversationMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.ModelConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("ModelConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.SendCommandEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("RobotConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WechatRobot.Infrastructure.Persistence.Entities.WorkToolOperationAuditEntity", b =>
                {
                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.GroupProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ReconciledGroupProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_worktool_operation_audit_reconciled_group");

                    b.HasOne("WechatRobot.Infrastructure.Persistence.Entities.RobotConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("RobotConfigId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
